### ISSUE TITLE
slug not coming in arabic language

### ISSUE THREAD

**Issue by ghost** [drobee/nova-sluggable#17]
I am adding the title in the Arabic letter but the auto slug is creating in English letters.
 
I couldn't find the languages which are supported- is Arabic is supported?

I am using the following code:- Slug::make('Slug')->slugLanguage('ar')

Thanks in advance!

**Comment by drobee** [comment]
@asharma16891 this field uses Laravel's own [`Illuminate\Support\Str::slug()`](https://github.com/illuminate/support/blob/master/Str.php#L465-L484) method to create the slug, and that uses [Voku's Portable ASCII lib](https://github.com/voku/portable-ascii/blob/master/src/voku/helper/ASCII.php#L577-L613). It supports Arabic language with [these replacements](https://github.com/voku/portable-ascii/blob/master/src/voku/helper/data/ascii_by_languages.php#L1551-L1597). 

I've just tested the Slug field with the `slugLanguage('ar')` option, and from the string `مرحبا` it generates the following slug: `mrhba`. Although i don't know much about the language, it seems quite right to me.

**Comment by ghost** [comment]
Thank you for your early reply.

But can i get slug same as title e.g if the title is مرحبا then slug field should have مرحبا

**Comment by drobee** [comment]
The goal of this package (and slugs in general) is to generate URL-friendly strings. I'm not a SEO expert, but i think Arabic characters in URLs would translate to HTML encoded strings and that is not the best way to manage URLs.

Maybe i just don't understand your problem. Can you elaborate on this a little bit please?

**Comment by ghost** [comment]
URL can be in Arabic, see the screenshot:- https://prnt.sc/plgd8v

I just want the slug to become in the same way the title was entered(Arabic). Right now it's coming in English which you also mentioned earlier. Screenshot:- https://prnt.sc/plggfn

Is it possible when i entered the title in Arabic than in the same way slug come?

**Comment by drobee** [comment]
I’m sorry, since this package utilizes Laravel’s slugger implementation, you should look for an other solution.
