### ISSUE TITLE
Help Text Doesn't Display

### ISSUE THREAD

**Issue by mdavis1982** [drobee/nova-sluggable#22]
When using this field in Laravel Nova 3.14.0, I'm not seeing the help text displayed underneath either of the two text inputs.

I've tried it in a fresh install and the behaviour is the same.

```php
SluggableText::make('Title')
    ->rules('required', 'string', 'min:3', 'max:255')
    ->help("The blog post's title"),
```

![image](https://user-images.githubusercontent.com/199807/98834255-e395a080-2436-11eb-9c78-4ec6a08bdcb3.png)

**Comment by marcreichel** [comment]
Same here!
