### ISSUE TITLE
Compatibility with Laravel 9

### ISSUE THREAD

**Issue by pdellepiane** [drobee/nova-sluggable#29]
composer require drobee/nova-sluggable    
Using version ^1.2 for drobee/nova-sluggable
./composer.json has been updated
Running composer update drobee/nova-sluggable
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - drobee/nova-sluggable[1.2.0, ..., 1.2.1] require illuminate/support 5.6.*|5.7.*|5.8.*|6.0.* -> found illuminate/support[v5.6.0, ..., 5.8.x-dev, v6.0.0, ..., v6.0.4] but these were not loaded, likely because it conflicts with another require.
    - drobee/nova-sluggable 1.2.2 requires illuminate/support 5.6.*|5.7.*|5.8.*|6.* -> found illuminate/support[v5.6.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev] but these were not loaded, likely because it conflicts with another require.
    - drobee/nova-sluggable 1.2.3 requires illuminate/support 5.6.*|5.7.*|5.8.*|6.*|7.* -> found illuminate/support[v5.6.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.
    - drobee/nova-sluggable[1.2.4, ..., 1.2.6] require illuminate/support 5.6.*|5.7.*|5.8.*|6.*|7.*|8.* -> found illuminate/support[v5.6.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires drobee/nova-sluggable ^1.2 -> satisfiable by drobee/nova-sluggable[1.2.0, ..., 1.2.6].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require drobee/nova-sluggable:*" to figure out if any version is installable, or "composer require drobee/nova-sluggable:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by drobee** [comment]
Hi @pdellepiane! 1.2.7 should fix this.
