### ISSUE TITLE
Slug was generated too slow

### ISSUE THREAD

**Issue by phuclh** [drobee/nova-sluggable#3]
Thank you for your Field, it works very well except the slug was generated really slow. When I finished typing, it takes 3-5 seconds to complete the slug field.

Does it cause by making too many requests for every button I typed?

Thank you!

**Comment by drobee** [comment]
Thanks for the feedback!

Each keystroke triggers an API call, but on my production environments these requests take only 100-150 ms.
Of course it depends on the client's bandwidth.

I'll try to optimize it.

**Comment by phuclh** [comment]
I think it can be better if the API call is triggered by `blur event`, not by `key up event`.
